### ISSUE TITLE
Is GPU support available?

### ISSUE THREAD

**Issue by mattiadg** [awslabs/sockeye#10]
Hi all,
I've tried to run a training on gpu with the following command 

```bash
python -m sockeye.train --source data/wmt15-de-en/train.en --target data/wmt15-de-en/train.de                --validation-source data/wmt15-de-en/valid.en --validation-target data/wmt15-de-en/valid.de --output models/ --device-ids 0
```

but got the following error 

```
Traceback (most recent call last):
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/sockeye-1.0.2-py3.6.egg/sockeye/train.py", line 265, in <module>
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/sockeye-1.0.2-py3.6.egg/sockeye/train.py", line 261, in main
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/sockeye-1.0.2-py3.6.egg/sockeye/training.py", line 192, in fit
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/mxnet/module/bucketing_module.py", line 298, in bind
    force_rebind=False, shared_module=None, grad_req=grad_req)
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/mxnet/module/module.py", line 388, in bind
    state_names=self._state_names)
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 216, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 312, in bind_exec
    shared_group))
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 632, in _bind_ith_exec
    context, self.logger)
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 610, in _get_or_reshape
    arg_arr = nd.zeros(arg_shape, context, dtype=arg_type)
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/mxnet/ndarray.py", line 1003, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype)
  File "<string>", line 15, in _zeros
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/mxnet/_ctypes/ndarray.py", line 72, in _imperative_invoke
    c_array(ctypes.c_char_p, [c_str(str(val)) for val in vals])))
  File "/hltmt0/data/digangi/anaconda3/lib/python3.6/site-packages/mxnet/base.py", line 84, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:16:21] src/c_api/c_api_ndarray.cc:392: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered
```

I don't get this error with --use-cpu.

I'm quite new to MXNet, so I can't get whether it is a problem of my installation.

Thanks,
Mattia

**Comment by fhieber** [comment]
Hi Mattia,

assuming that you are running this on a machine with a GPU and CUDA 8.0, it looks like you have an MXNet version installed without CUDA support. (This is the one you get when running pip install mxnet==0.10.0).

Try
```pip install mxnet-cu80==0.10.0```

**Comment by mattiadg** [comment]
Thank you, this solved the problem!

**Comment by mattiadg** [comment]
Thank you, this solved the problem!

**Comment by tdomhan** [comment]
great! We're currently updating the documentation about this, as the error message is extremely cryptic.
