### ISSUE TITLE
Yaml dependency missing

### ISSUE THREAD

**Issue by lefterav** [awslabs/sockeye#102]
On a fresh installation, I got this exception right after the first run

```
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/elav01/.local/lib/python3.5/site-packages/sockeye/train.py", line 33, in <module>
    from . import attention
  File "/home/elav01/.local/lib/python3.5/site-packages/sockeye/attention.py", line 22, in <module>
    from . import config
  File "/home/elav01/.local/lib/python3.5/site-packages/sockeye/config.py", line 16, in <module>
    import yaml
ImportError: No module named 'yaml'
```

`pip install pyyaml` solved it.  I guess it should

**Comment by tdomhan** [comment]
thanks for creating the issue. :)
How did you install Sockeye? The [requirements.txt](https://github.com/awslabs/sockeye/blob/master/requirements.txt) and therefore also the [pypi package](https://pypi.python.org/pypi/sockeye/1.1.1) state the pyyaml dependency. I'm wondering how this happened and how we can prevent this in the future.

**Comment by lefterav** [comment]
Hi, thanks for the response and sorry I didn't give more details earlier. I installed sockeye on a GPU-enabled computer using requirements.gpu-cu75.txt as per the instructions of the README in the github. This requirements file (as well as the one for CUDA v8.0) does not include pyyaml .

**Comment by tdomhan** [comment]
oh, good point! I'll add the dependency there as well. Thanks for reporting.
