### ISSUE TITLE
ValueError: Unsupported nproc_per_node value: 4(x2)

### ISSUE THREAD

**Issue by SamuelLarkin** [awslabs/sockeye#1038]
Hi,
  I wanted to use multiple nodes to train `Sockeye` but I getting `ValueError: Unsupported nproc_per_node value: 4(x2)`.  My `slurm` cluster sets `SLURM_TASKS_PER_NODE='4(x2)'`.

# Environment Variables
Here are relevant environment variables.
```
SLURM_CPUS_ON_NODE=32
SLURM_CPUS_PER_TASK=6
SLURM_JOB_CPUS_PER_NODE='32(x2)'
SLURM_JOB_GRES=0,1,2,3
SLURM_JOB_NUM_NODES=2
SLURM_MEM_PER_NODE=98304
SLURM_NNODES=2
SLURM_NODEID=0
SLURM_NPROCS=8
SLURM_NTASKS=8
SLURM_TASKS_PER_NODE='4(x2)'
SLURM_TASK_PID=438
```

# Stack Trace
```bash
ERROR:torch.distributed.elastic.multiprocessing.errors.error_handler:{
  "message": {
    "message": "ValueError: Unsupported nproc_per_node value: 4(x2)",
    "extraInfo": {
      "py_callstack": "Traceback (most recent call last):\n  File \"/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/dis
      "timestamp": "1649095601"
    }
  }
}
Traceback (most recent call last):
  File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/distributed/run.py", line 564, in determine_local_world_size
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: '4(x2)'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.10.0', 'console_scripts', 'torchrun')())
  File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 3
    return f(*args, **kwargs)
  File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/distributed/run.py", line 719, in main
    run(args)
  File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/distributed/run.py", line 709, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/distributed/run.py", line 617, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/gpfs/projects/DT/mtp/WMT20/opt/miniconda3/envs/sockeye-3.1.0/lib/python3.8/site-packages/torch/distributed/run.py", line 582, in determine_local_world_size
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}")
ValueError: Unsupported nproc_per_node value: 4(x2)
```

# SLURM's Documentation
As per `sbatch`'s [documentation](https://slurm.schedmd.com/sbatch.html), `SLURM_TASKS_PER_NODE='4(x2)'` should be a valid string representing the number of task/proc per node.

**SLURM_JOB_CPUS_PER_NODE**
Count of CPUs available to the job on the nodes in the allocation, using the format CPU_count[(xnumber_of_nodes)][,CPU_count [(xnumber_of_nodes)] ...]. For example: SLURM_JOB_CPUS_PER_NODE='72(x2),36' indicates that on the first and second nodes (as listed by SLURM_JOB_NODELIST) the allocation has 72 CPUs, while the third node has 36 CPUs. NOTE: The select/linear plugin allocates entire nodes to jobs, so the value indicates the total count of CPUs on allocated nodes. The select/cons_res and select/cons_tres plugins allocate individual CPUs to jobs, so this number indicates the number of CPUs allocated to the job.

# Sockeye Version
I'm using `sockeye==3.1.0`

**Comment by mjdenkowski** [comment]
It looks like this conversation moved to #1039.
