### ISSUE TITLE
Out of memory exception after releasing GPUs in epoch 0

### ISSUE THREAD

**Issue by ejkitchen** [awslabs/sockeye#1055]
Hello,

How can I diagnose the out-of-memory error below? It's not clear to me why it's happening at that location but I suspect something was trying to perhaps(?) create a copy of a very large ndarray. I've searched for other sockeye memory error issues and this doesn't appear to be a CUDA /GPU memory issue at first glance. How can we better diagnose the source of this error?

We are training on a dedicated DGXA100 server with 2TB of RAM and 8 A100 GPUs with 80Gb of GPU RAM each. The sockeye training is the only process running (apart from other NVIDIA & system services) so most of the system RAM is free and nothing else is consuming the GPUs. If you look at the GPU RAM usage below, most GPUs are at ~87% and the last one at ~35%

Here are the logs:
===========
[2022-07-13:15:46:23:INFO:sockeye.training:__call__] E=0 B=79700	s/sec=433.90 tok/sec=12816.83 u/sec=0.07	ppl=374.235978 
[2022-07-13:15:46:30:INFO:sockeye.training:__call__] E=0 B=79750	s/sec=480.49 tok/sec=11463.11 u/sec=0.07	ppl=374.079897 
[2022-07-13:15:46:38:INFO:sockeye.training:__call__] E=0 B=79800	s/sec=475.42 tok/sec=10885.53 u/sec=0.06	ppl=373.886276 
[2022-07-13:15:46:47:INFO:sockeye.training:__call__] E=0 B=79850	s/sec=389.05 tok/sec=10893.50 u/sec=0.06	ppl=373.733448 
[2022-07-13:15:46:55:INFO:sockeye.training:__call__] E=0 B=79900	s/sec=442.24 tok/sec=10866.43 u/sec=0.06	ppl=373.558397 
[2022-07-13:15:47:02:INFO:sockeye.training:__call__] E=0 B=79950	s/sec=435.77 tok/sec=11598.26 u/sec=0.07	ppl=373.405683 
[2022-07-13:15:47:11:INFO:sockeye.training:__call__] E=0 B=80000	s/sec=396.52 tok/sec=11712.64 u/sec=0.06	ppl=373.273127 
[2022-07-13:15:47:27:INFO:root:save_parameters] Saved params to "/model/model1/params.00004"
[2022-07-13:15:47:27:INFO:sockeye.training:_create_checkpoint] Checkpoint [4]	Updates=800 Epoch=0 Samples=5541888 Time-cost=3414.015 Updates/sec=0.059
[2022-07-13:15:47:27:INFO:sockeye.training:_create_checkpoint] Checkpoint [4]	Train-ppl=373.273127
[2022-07-13:16:00:52:INFO:sockeye.training:_evaluate] Checkpoint [4]	Validation-ppl=300.643071	Validation-bleu=0.013280	Validation-chrf=0.222014	Validation-rouge1=0.170945	Validation-rouge2=0.027774	Validation-rougel=0.130451	Validation-length-ratio-mse=1.131029	Validation-avg-sec-per-sent=0.090980	Validation-decode-walltime=765.779070
[2022-07-13:16:00:52:INFO:sockeye.training:_determine_improvement] Validation-perplexity improved to 300.643071 (delta=125.811331).
[2022-07-13:16:00:52:INFO:sockeye.training:_update_best_params] '/model/model1/params.best' now points to 'params.00004'
[2022-07-13:16:01:36:INFO:sockeye.training:_save_trainer_states] Saved optimizer states to "/model/model1/mx_optimizer_best.pkl"
[2022-07-13:16:01:36:INFO:sockeye.training:_save_lr_scheduler] Saved 'LearningRateSchedulerPlateauReduce(reduce_factor=0.90, reduce_num_not_improved=8, num_not_improved=0, base_lr=0.0005, lr=0.0005, warmup=0, warmed_up=True)' to '/model/model1/lr_scheduler_best.pkl'
[2022-07-13:16:01:36:INFO:sockeye.utils:log_gpu_memory_usage] GPU 0: 74253/85198 MB (87.15%) GPU 1: 74306/85198 MB (87.22%) GPU 2: 74314/85198 MB (87.23%) GPU 3: 74109/85198 MB (86.98%) GPU 4: 74260/85198 MB (87.16%) GPU 5: 74283/85198 MB (87.19%) GPU 6: 74272/85198 MB (87.18%) GPU 7: 30400/85198 MB (35.68%)
[2022-07-13:16:02:17:INFO:sockeye.training:_save_trainer_states] Saved optimizer states to "/model/model1/tmp.training_state/mx_optimizer_last.pkl"
[2022-07-13:16:02:17:INFO:sockeye.training:_save_lr_scheduler] Saved 'LearningRateSchedulerPlateauReduce(reduce_factor=0.90, reduce_num_not_improved=8, num_not_improved=0, base_lr=0.0005, lr=0.0005, warmup=0, warmed_up=True)' to '/model/model1/tmp.training_state/lr_scheduler_last.pkl'
[2022-07-13:16:04:03:INFO:sockeye.utils:__exit__] Releasing GPU 7.
[2022-07-13:16:04:03:INFO:sockeye.utils:__exit__] Releasing GPU 6.
[2022-07-13:16:04:03:INFO:sockeye.utils:__exit__] Releasing GPU 5.
[2022-07-13:16:04:03:INFO:sockeye.utils:__exit__] Releasing GPU 4.
[2022-07-13:16:04:03:INFO:sockeye.utils:__exit__] Releasing GPU 3.
[2022-07-13:16:04:03:INFO:sockeye.utils:__exit__] Releasing GPU 2.
[2022-07-13:16:04:03:INFO:sockeye.utils:__exit__] Releasing GPU 1.
[2022-07-13:16:04:03:INFO:sockeye.utils:__exit__] Releasing GPU 0.
[2022-07-13:16:04:03:ERROR:root:exception_hook] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.8/dist-packages/sockeye/train.py", line 1151, in <module>
    main()
  File "/usr/local/lib/python3.8/dist-packages/sockeye/train.py", line 906, in main
    train(args)
  File "/usr/local/lib/python3.8/dist-packages/sockeye/train.py", line 1146, in train
    training_state = trainer.fit(train_iter=train_iter, validation_iter=eval_iter, checkpoint_decoder=cp_decoder)
  File "/usr/local/lib/python3.8/dist-packages/sockeye/training.py", line 242, in fit
    did_grad_step = self._step(batch=train_iter.next())
  File "/usr/local/lib/python3.8/dist-packages/sockeye/training.py", line 352, in _step
    loss_func.metric.update(loss_value.asscalar(), num_samples.asscalar())
  File "/usr/local/lib/python3.8/dist-packages/mxnet/ndarray/ndarray.py", line 2590, in asscalar
    return self.asnumpy()[0]
  File "/usr/local/lib/python3.8/dist-packages/mxnet/ndarray/ndarray.py", line 2568, in asnumpy
    check_call(_LIB.MXNDArraySyncCopyToCPU(
  File "/usr/local/lib/python3.8/dist-packages/mxnet/base.py", line 246, in check_call
    raise get_last_ffi_error()
mxnet.base.MXNetError: Traceback (most recent call last):
  File "../src/ndarray/../operator/tensor/./../mxnet_op.h", line 1120
Name: Check failed: err == cudaSuccess (2 vs. 0) : mxnet_generic_kernel ErrStr:out of memory

**Comment by ejkitchen** [comment]
Ok, thanks! Starting the conversion now.
