### ISSUE TITLE
How to finetune no-factor translation model with factors?

### ISSUE THREAD

**Issue by SKT-T1-Thecai** [awslabs/sockeye#1089]
Hi,
I have trained an EN-ZH translation model with Sockeye 1 without factors. Now I want to finetune it with additional data and I extract 2 source factors.
The scripts I used are as follows:
`nohup python -m sockeye.train  \
--prepared-data /raid/multilingual_models/en-zh-v2/en-zh.prepared/ft_prepare \
--params /raid/multilingual_models/en-zh-v2/en-zh.prepared/btransformer/params.best \
--validation-source /raid/multilingual_models/en-zh-v2/en-zh.prepared/valid_onehot.src \
--validation-target /raid/multilingual_models/en-zh-v2/en-zh.prepared/valid_onehot.tgt \
--device-ids 0 1 2 3 \
--source-factors-num-embed 1024 \
--transformer-model-size 1024 \
--transformer-feed-forward-num-hidden 4096 \
--transformer-attention-heads 16 \
--source-factors-combine sum \
--validation-source-factors /raid/multilingual_models/en-zh-v2/en-zh.prepared/valid_bpe_factor.src \
/raid/multilingual_models/en-zh-v2/en-zh.prepared/valid_label_factor.src \
--output /raid/multilingual_models/en-zh-v2/en-zh.prepared/finetune-enzh \
--batch-type sentence \
--batch-size 256 \
--update-interval 2 \
--max-num-checkpoint-not-improved 16 \
--metrics perplexity \
--optimized-metric perplexity \
--checkpoint-interval 5000 \
--optimizer adam \
--decode-and-evaluate -1 \
--max-seq-len 100:100 \
--loss cross-entropy \
--seed 20230614 \`
And the report is
`[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "/home/jianwei/anaconda3/envs/mxnet-multi/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/jianwei/anaconda3/envs/mxnet-multi/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/raid/tza/sockeye-master-mxnet/sockeye/train.py", line 984, in <module>
    main()
  File "/raid/tza/sockeye-master-mxnet/sockeye/train.py", line 838, in main
    train(args)
  File "/raid/tza/sockeye-master-mxnet/sockeye/train.py", line 980, in train
    existing_parameters=args.params)
  File "/raid/tza/sockeye-master-mxnet/sockeye/training.py", line 676, in fit
    self._initialize_parameters(existing_parameters, allow_missing_parameters)
  File "/raid/tza/sockeye-master-mxnet/sockeye/training.py", line 1027, in _initialize_parameters
    self.model.load_params_from_file(params, allow_missing_params=allow_missing_params)
  File "/raid/tza/sockeye-master-mxnet/sockeye/training.py", line 458, in load_params_from_file
    allow_missing=allow_missing_params)
  File "/home/jianwei/anaconda3/envs/mxnet-multi/lib/python3.6/site-packages/mxnet/module/bucketing_module.py", line 207, in set_params
    allow_missing=allow_missing, force_init=force_init)
  File "/home/jianwei/anaconda3/envs/mxnet-multi/lib/python3.6/site-packages/mxnet/module/bucketing_module.py", line 250, in init_params
    force_init=force_init, allow_extra=allow_extra)
  File "/home/jianwei/anaconda3/envs/mxnet-multi/lib/python3.6/site-packages/mxnet/module/module.py", line 309, in init_params
    _impl(desc, arr, arg_params)
  File "/home/jianwei/anaconda3/envs/mxnet-multi/lib/python3.6/site-packages/mxnet/module/module.py", line 300, in _impl
    raise RuntimeError("%s is not presented" % name)
RuntimeError: source_embed_factor0_weight is not presented
`
Is my operation wrong or it is not allowed to finetue a no-factor model with factors?

**Comment by tdomhan** [comment]
When fine-tuning the inputs are expected to be identical, so either have and not have factors. So unfortunately you would need to add the source factors already to the base model training. (a hacky work around would be to manually extend the embedding matrices with factor embeddings initialized randomly, but that is not officially supported)
