### ISSUE TITLE
NameError: name 'broadcast_maximum' is not defined

### ISSUE THREAD

**Issue by lianghong** [awslabs/sockeye#117]
OS : Ubuntu 16.04
Python 3.5.2
mxnet :0.11.1

sockeye : 1.5.1
Run :

error:
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/lianghong/Project/github/sockeye/sockeye/train.py", line 417, in <module>
    main()
  File "/home/lianghong/Project/github/sockeye/sockeye/train.py", line 413, in main
    mxmonitor_stat_func=args.monitor_stat_func)
  File "/home/lianghong/Project/github/sockeye/sockeye/training.py", line 246, in fit
    mxmonitor=monitor)
  File "/home/lianghong/Project/github/sockeye/sockeye/training.py", line 324, in _fit
    self.module.update_metric(metric_train, batch.label)
  File "/home/lianghong/Project/github/mxnet/python/mxnet/module/bucketing_module.py", line 488, in update_metric
    self._curr_module.update_metric(eval_metric, labels)
  File "/home/lianghong/Project/github/mxnet/python/mxnet/module/module.py", line 735, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "/home/lianghong/Project/github/mxnet/python/mxnet/module/executor_group.py", line 582, in update_metric
    eval_metric.update_dict(labels_, preds)
  File "/home/lianghong/Project/github/mxnet/python/mxnet/metric.py", line 280, in update_dict
    metric.update_dict(labels, preds)
  File "/home/lianghong/Project/github/mxnet/python/mxnet/metric.py", line 108, in update_dict
    self.update(label, pred)
  File "/home/lianghong/Project/github/mxnet/python/mxnet/metric.py", line 657, in update
    loss -= ndarray.sum(ndarray.log(ndarray.maximum(1e-10, pred))).asscalar()
  File "/home/lianghong/Project/github/mxnet/python/mxnet/ndarray/ndarray.py", line 1793, in maximum
    broadcast_maximum,
NameError: name 'broadcast_maximum' is not defined

Many thanks.

**Comment by fhieber** [comment]
Hi,

thanks for submitting this issue. Can you provide the command you ran?
Also, Sockeye depends on mxnet-0.10.0 currently. We haven't tested with 0.11.1 yet.

**Comment by lianghong** [comment]
the command is :

python3 -m sockeye.train --source train.de \
        --target train.en \
        --validation-source newstest2016.tc.de \
        --validation-target newstest2016.tc.en \
        --num-embed 128 \
        --rnn-num-hidden 512 \
        --attention-type dot \
        --word-min-count 10 \
        --output model

**Comment by tdomhan** [comment]
could you try running with mxnet version 0.10. As this is the latest stable release this is the version we depend on. Once 0.11 is released we will switch over to the newer version of MXNet.

**Comment by tdomhan** [comment]
I'll close for now. Let us now if this doesn't solve the issue.
