### ISSUE TITLE
Sacrebleu data issue: statmt.org no longer has "wmt14"

### ISSUE THREAD

**Issue by okuchaiev** [awslabs/sockeye#441]
It seems that wmt14 folder no longer exists here:  ```http://statmt.org/wmt14/test-filtered.tgz```. The website itself (statmt.org) is not down.
This means that whenever I call a command like this: ```cat out.txt | sacrebleu -t wmt14 -l en-de -lc --tokenize intl``` for the first time I get an error (see below)

Should these test cases be hosted elsewhere?

>sacreBLEU: Downloading http://statmt.org/wmt14/test-filtered.tgz to /home/okuchaiev/.sacrebleu/wmt14/test-filtered.tgz
Traceback (most recent call last):
  File "/home/okuchaiev/anaconda3/lib/python3.6/urllib/request.py", line 1318, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/home/okuchaiev/anaconda3/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/home/okuchaiev/anaconda3/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/home/okuchaiev/anaconda3/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/home/okuchaiev/anaconda3/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/home/okuchaiev/anaconda3/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/okuchaiev/anaconda3/lib/python3.6/http/client.py", line 936, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/home/okuchaiev/anaconda3/lib/python3.6/socket.py", line 722, in create_connection
    raise err
  File "/home/okuchaiev/anaconda3/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "/home/okuchaiev/anaconda3/lib/python3.6/site-packages/sacrebleu.py", line 903, in download_test_set
    with urllib.request.urlopen(dataset) as f, open(tarball, 'wb') as out:
  File "/home/okuchaiev/anaconda3/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/home/okuchaiev/anaconda3/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/home/okuchaiev/anaconda3/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/home/okuchaiev/anaconda3/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/home/okuchaiev/anaconda3/lib/python3.6/urllib/request.py", line 1346, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/home/okuchaiev/anaconda3/lib/python3.6/urllib/request.py", line 1320, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 113] No route to host>

>During handling of the above exception, another exception occurred:

>-Traceback (most recent call last):
  File "/home/okuchaiev/anaconda3/bin/sacrebleu", line 11, in <module>
    sys.exit(main())
  File "/home/okuchaiev/anaconda3/lib/python3.6/site-packages/sacrebleu.py", line 1281, in main
    _, *refs = download_test_set(args.test_set, args.langpair)
  File "/home/okuchaiev/anaconda3/lib/python3.6/site-packages/sacrebleu.py", line 905, in download_test_set
    except ssl.SSLError:
NameError: name 'ssl' is not defined

**Comment by mjpost** [comment]
Hi,

statmt.org was down this morning (and maybe last night?) due to the power being cut at a building at U Edinburgh. It seems back up to me now, though — I can download the test set you listed and access the site. The site is pretty reliable so I think you just got unlucky.

matt
