### ISSUE TITLE
Sockeye Training stopped halfway

### ISSUE THREAD

**Issue by mahjabeen-sust** [awslabs/sockeye#462]
My training ran for 3 epochs with 4000 batches. Then a Value error occurred. The log file says this:

[2018-06-28:23:59:19:INFO:sockeye.training:start_decoder] Starting process: Decoder-1
[2018-06-28:23:59:23:ERROR:__main__:exception_hook] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/sockeye/train.py", line 880, in <module>
    main()
  File "/usr/local/lib/python3.5/dist-packages/sockeye/train.py", line 764, in main
    train(args)
  File "/usr/local/lib/python3.5/dist-packages/sockeye/train.py", line 876, in train
    existing_parameters=args.params)
  File "/usr/local/lib/python3.5/dist-packages/sockeye/training.py", line 576, in fit
    self._update_metrics(metric_train, metric_val, process_manager)
  File "/usr/local/lib/python3.5/dist-packages/sockeye/training.py", line 747, in _update_metrics
    self.tflogger.log_metrics(metrics=tf_metrics, checkpoint=self.state.checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/sockeye/training.py", line 1033, in log_metrics
    self.sw.add_histogram(tag=name, values=value, bins=100, global_step=checkpoint)
  File "/usr/local/lib/python3.5/dist-packages/mxboard/writer.py", line 402, in add_histogram
    self._file_writer.add_summary(histogram_summary(tag, values, bins), global_step)
  File "/usr/local/lib/python3.5/dist-packages/mxboard/summary.py", line 148, in histogram_summary
    hist = _make_histogram(values.astype(float), bins)
  File "/usr/local/lib/python3.5/dist-packages/mxboard/summary.py", line 156, in _make_histogram
    counts, limits = np.histogram(values, bins=bins)
  File "/usr/local/lib/python3.5/dist-packages/numpy/lib/function_base.py", line 670, in histogram
    'range parameter must be finite.')
ValueError: range parameter must be finite.

How to fix this?

**Comment by davvil** [comment]
Hi! Thanks for reporting this issue.

This may be related to an effect that we have seem sometimes where the training diverges and numpy takes a high value as infinity. Could you please post the evolution of the perplexity for the last updates, as reported in the log file?

**Comment by mahjabeen-sust** [comment]
Hi,
These are the last lines of the log file before it showed error:
[2018-06-28:23:58:31:INFO:sockeye.training:__call__] Epoch[3] Batch [4000]	Speed: 35.22 samples/sec 1054.00 tokens/sec 0.20 updates/sec	perplexity=977.218884
[2018-06-28:23:58:32:INFO:root:save_params_to_file] Saved params to "/home/cse/neela/sockeye-nmt/wmt_model/params.00001"
[2018-06-28:23:58:32:INFO:sockeye.training:fit] Checkpoint [1]	Updates=4000 Epoch=3 Samples=673205 Time-cost=40459.567 Updates/sec=0.099
[2018-06-28:23:58:32:INFO:sockeye.training:fit] Checkpoint [1]	Train-perplexity=977.218884
[2018-06-28:23:59:19:INFO:sockeye.training:fit] Checkpoint [1]	Validation-perplexity=2131.587664
[2018-06-28:23:59:19:INFO:sockeye.training:start_decoder] Starting process: Decoder-1

**Comment by fhieber** [comment]
Agreed that this error is likely to be the result of `nan` values in the parameters OR in the gradients which are also serialized through mxboard. I am not sure though if we want to check for `nan` values with every update just for a more informative error message; this could be costly.
If one runs into such a situation the training probably has probably diverged anyway and this set of (hyper-)parameters isn't working well.

**Comment by tdomhan** [comment]
Have you run into this issue repeatedly? Could you provide a larger portion of the log in order to see whether training is diverging?
I agree that when you see a nan something then probably training diverged and it would also not help to print a better error message. In case we still wanted to do so, or avoid this issue in logging there's also `np.nan_to_num` `np.isnan`.

**Comment by fhieber** [comment]
Closing due to inactivity. If the issue resurfaces, feel free to reopen.
