### ISSUE TITLE
--softmax-temperature doesn't seem to work in sockeye.translate

### ISSUE THREAD

**Issue by edwdh** [awslabs/sockeye#489]
It seems that setting `--softmax-temperature` causes the following error:

```
[ERROR:__main__] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/edwardhu/.local/lib/python3.5/site-packages/sockeye/translate.py", line 244, in <module>
    main()
  File "/home/edwardhu/.local/lib/python3.5/site-packages/sockeye/translate.py", line 42, in main
    run_translate(args)
  File "/home/edwardhu/.local/lib/python3.5/site-packages/sockeye/translate.py", line 86, in run_translate
    override_dtype=args.override_dtype)
  File "/home/edwardhu/.local/lib/python3.5/site-packages/sockeye/inference.py", line 448, in load_models
    inference_model.initialize(max_input_len, get_max_output_length)
  File "/home/edwardhu/.local/lib/python3.5/site-packages/sockeye/inference.py", line 128, in initialize
    self.decoder_module, self.decoder_default_bucket_key = self._get_decoder_module()
  File "/home/edwardhu/.local/lib/python3.5/site-packages/sockeye/inference.py", line 249, in _get_decoder_module
    context=self.context)
  File "/home/edwardhu/.local/lib/python3.5/site-packages/mxnet/module/bucketing_module.py", line 75, in __init__
    symbol, data_names, label_names = self._call_sym_gen(default_bucket_key)
  File "/home/edwardhu/.local/lib/python3.5/site-packages/mxnet/module/bucketing_module.py", line 108, in _call_sym_gen
    return self._sym_gen(*args, **kwargs)
  File "/home/edwardhu/.local/lib/python3.5/site-packages/sockeye/inference.py", line 238, in sym_gen
    logits /= self.softmax_temperature
  File "/home/edwardhu/.local/lib/python3.5/site-packages/mxnet/symbol/symbol.py", line 233, in __itruediv__
    raise NotImplementedForSymbol(self.__itruediv__, '/=', other)
mxnet.base.NotImplementedForSymbol: Function __itruediv__ (namely operator "/=") with arguments (<class 'float'>) is not implemented for Symbol and only available in NDArray.
```

**Comment by tdomhan** [comment]
thanks for reporting! I can reproduce the issue. I'll let you know when we have a fix.
