### ISSUE TITLE
IndexError when loading data during training

### ISSUE THREAD

**Issue by tanggongbo** [awslabs/sockeye#509]
Hi, I met a problem during model (RNN-RNN model) training. The exception raised when reading the data. 
However, I could train other models (with different data or different models (Transformer-RNN) ) successfully. Thanks! 

I am using Sockeye Version 1.18.27 (Branch: acl18), MXNet Version 1.2.1. 
Here is the error information:

[INFO:sockeye.training] Epoch[11] Batch [896100]        Speed: 132.76 samples/sec 4662.53 tokens/sec 1.79 updates/sec   perplexity=5.321818
[INFO:sockeye.utils] Releasing GPU 3.
[INFO:sockeye.utils] Releasing GPU 2.
[ERROR:__main__] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/mnt/snotra0/gtang/sockeye-module/sockeye/sockeye/train.py", line 912, in <module>
    main()
  File "/mnt/snotra0/gtang/sockeye-module/sockeye/sockeye/train.py", line 796, in main
    train(args)
  File "/mnt/snotra0/gtang/sockeye-module/sockeye/sockeye/train.py", line 908, in train
    existing_parameters=args.params)
  File "/mnt/snotra0/gtang/sockeye-module/sockeye/sockeye/training.py", line 550, in fit
    next_data_batch = train_iter.next()
  **File "/mnt/snotra0/gtang/sockeye-module/sockeye/sockeye/data_io.py", line 1580, in next
    source = self.data.source[i][j:j + batch_size]**
  File "/home/gtang/.local/lib/python3.5/site-packages/mxnet/ndarray/ndarray.py", line 506, in __getitem__
    return self._get_nd_basic_indexing(key)
  File "/home/gtang/.local/lib/python3.5/site-packages/mxnet/ndarray/ndarray.py", line 783, in _get_nd_basic_indexing
    return self._slice(key.start, key.stop)
  File "/home/gtang/.local/lib/python3.5/site-packages/mxnet/ndarray/ndarray.py", line 898, in _slice
    start, stop, _ = _get_index_range(start, stop, self.shape[0])
  File "/home/gtang/.local/lib/python3.5/site-packages/mxnet/ndarray/ndarray.py", line 2177, in _get_index_range
    **raise IndexError('Slicing stop %d exceeds limit of %d' % (stop, length))
IndexError: Slicing stop 1325227 exceeds limit of 1325226**

**Comment by tanggongbo** [comment]
Problem disappears when I retrained the model from scratch.
