### ISSUE TITLE
No error thrown when training with source factor files but no validation source factor files given

### ISSUE THREAD

**Issue by fhieber** [awslabs/sockeye#513]
Sockeye does not throw in the beginning of training when using plain training data + source factor files but without providing a corresponding source factor file for the validation data.
It will then crash at the first checkpoint with a cryptic error message:
```
[INFO:sockeye.training] Checkpoint [1]	Train-perplexity=928.900834
infer_shape error. Arguments:
  source: (10, 10, 1)
  target: (10, 10)
  target_label: (10, 10)
[ERROR:__main__] Uncaught exception
Traceback (most recent call last):
  File "/Users/fhieber/miniconda3/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/fhieber/miniconda3/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/fhieber/workspace/nmt/src/Sockeye/sockeye/train.py", line 881, in <module>
    main()
  File "/Users/fhieber/workspace/nmt/src/Sockeye/sockeye/train.py", line 756, in main
    train(args)
  File "/Users/fhieber/workspace/nmt/src/Sockeye/sockeye/train.py", line 877, in train
    existing_parameters=args.params)
  File "/Users/fhieber/workspace/nmt/src/Sockeye/sockeye/training.py", line 573, in fit
    self._evaluate(validation_iter, metric_val)
  File "/Users/fhieber/workspace/nmt/src/Sockeye/sockeye/training.py", line 711, in _evaluate
    self.model.evaluate(val_iter, val_metric)
  File "/Users/fhieber/workspace/nmt/src/Sockeye/sockeye/training.py", line 240, in evaluate
    self.module.forward(eval_batch, is_train=False)
  File "/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/module/bucketing_module.py", line 456, in forward
    self._curr_module.forward(data_batch, is_train=is_train)
  File "/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/module/module.py", line 610, in forward
    self.reshape(new_dshape, new_lshape)
  File "/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/module/module.py", line 471, in reshape
    self._exec_group.reshape(self._data_shapes, self._label_shapes)
  File "/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 382, in reshape
    self.bind_exec(data_shapes, label_shapes, reshape=True)
  File "/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/module/executor_group.py", line 358, in bind_exec
    allow_up_sizing=True, **dict(data_shapes_i + label_shapes_i))
  File "/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/executor.py", line 402, in reshape
    arg_shapes, _, aux_shapes = self._symbol.infer_shape(**kwargs)
  File "/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/symbol/symbol.py", line 990, in infer_shape
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/symbol/symbol.py", line 1120, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/Users/fhieber/miniconda3/lib/python3.6/site-packages/mxnet/base.py", line 149, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator source_embed_factor_split: [15:36:18] src/operator/./slice_channel-inl.h:208: Check failed: dshape[real_axis] % param_.num_outputs == 0U (1 vs. 0) You are trying to split the 2-th axis of input tensor with shape [10,10,1] into num_outputs=2 evenly sized chunks, but this is not possible because 2 does not evenly divide 1
```

**Comment by mjpost** [comment]
It looks like [the check is there, but is indented incorrectly](https://github.com/awslabs/sockeye/blob/3b8865e0952033c5a0a5ac0065bda8465ec9d258/sockeye/train.py#L282).
