### ISSUE TITLE
travis CRON job fails due to connection timeout in Autopilot test

### ISSUE THREAD

**Issue by fhieber** [awslabs/sockeye#522]
It seems that travis CRON jobs are failing due to a connection timeout in the Autopilot test when trying to download this file (for example see here: https://travis-ci.org/awslabs/sockeye/jobs/423743734#L6676):
```
Download: https://nlp.stanford.edu/projects/nmt/data/wmt14.en-de/newstest2014.de 
Traceback (most recent call last):
  File "/opt/python/3.5.6/lib/python3.5/urllib/request.py", line 1254, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/opt/python/3.5.6/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/opt/python/3.5.6/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/opt/python/3.5.6/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/opt/python/3.5.6/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/opt/python/3.5.6/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/opt/python/3.5.6/lib/python3.5/http/client.py", line 1253, in connect
    super().connect()
  File "/opt/python/3.5.6/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/python/3.5.6/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/opt/python/3.5.6/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out
```

Maybe the URL has changed?

**Comment by mjdenkowski** [comment]
Looks like the Stanford NLP site that hosts the files is down.  I added #523 to route around this.

**Comment by fhieber** [comment]
Thanks!
