### ISSUE TITLE
Training deadlock/similar full stop after starting decoder

### ISSUE THREAD

**Issue by sliedes** [awslabs/sockeye#529]
On a recent git HEAD (9de53f90), I have seen my model run for a few hours at a time, after which it stops progressing. The last log line is always "Starting process: Decoder-N" for some number N. In each run, several decoders have successfully finished before the deadlocking one.

One potentially significant change I have made: There was no mxnet-cu91mkl 1.2.1 in pypi, so I changed the requirement to 1.2.1.post1.

I first thought this was a symptom of the nvdia-smi memory measurement thing, since it threw errors like this (even after the recent "tolerate nvidia-smi failures" fix):

```
[2018-09-05:17:27:08:ERROR:sockeye.utils:get_gpu_memory_usage] Failed calling nvidia-smi to query memory usage.
Traceback (most recent call last):
  File "/home/sliedes/projects/sockeye/sockeye/utils.py", line 472, in get_gpu_memory_usage
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/lib64/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib64/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 14] Bad address: 'nvidia-smi'
```

However, the deadlocks still happen after disabling the used-gpu-memory metrics altogether by commenting out the calling code in EarlyStoppingTrainer._update_metrics.

After the deadlock, both CPU and GPU usage are 0 %. There are no GPU errors in dmesg. The number of previous successful Decoder processes varies; I have seen at least 6 and 18.

After interrupting the process (ctrl-c) while deadlocked, I get this backtrace:

```
[2018-09-05:21:23:43:INFO:sockeye.training:start_decoder] Starting process: Decoder-16
[2018-09-06:09:44:28:INFO:sockeye.utils:__exit__] Releasing GPU 0.
[2018-09-06:09:44:28:ERROR:__main__:exception_hook] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/sliedes/projects/sockeye/sockeye/train.py", line 885, in <module>
    main()
  File "/home/sliedes/projects/sockeye/sockeye/train.py", line 760, in main
    train(args)
  File "/home/sliedes/projects/sockeye/sockeye/train.py", line 881, in train
    existing_parameters=args.params)
  File "/home/sliedes/projects/sockeye/sockeye/training.py", line 578, in fit
    self._update_metrics(metric_train, metric_val, process_manager)
  File "/home/sliedes/projects/sockeye/sockeye/training.py", line 740, in _update_metrics
    process_manager.start_decoder(self.state.checkpoint)
  File "/home/sliedes/projects/sockeye/sockeye/training.py", line 1135, in start_decoder
    self.decoder_process.start()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 105, in start
    self._popen = self._Popen(self)
  File "/usr/lib64/python3.6/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/lib64/python3.6/multiprocessing/popen_spawn_posix.py", line 62, in _launch
    f.write(fp.getbuffer())
KeyboardInterrupt
```

The command line I use to train is

`python -m sockeye.train -d models/en-multi-char/ -vs models/en-multi-char/src.val -vt models/en-multi-char/tgt.val --encoder transformer-with-conv-embed --decoder transformer -o models/en-multi-char/ --shared-vocab --max-seq-len 300:300 --num-embed 32 --transformer-model-size 32`.

Log file from one of the deadlocking runs: [run1.txt](https://github.com/awslabs/sockeye/files/2358682/run1.txt)

The systems is an x86_64 box running Arch Linux with kernel 4.18.4-arch1-1-ARCH. The GPU is an Nvidia 1080 Ti.

**Comment by fhieber** [comment]
Thanks for submitting this issue. Do the deadlocks ONLY happen when using the CheckpointDecoder, i.e. when `--decode-and-evaluate >0`?

**Comment by sliedes** [comment]
So far I have not seen it happen with --decode-and-evaluate 0.

**Comment by fhieber** [comment]
Are running the training inside a Docker container by any chance?

**Comment by sliedes** [comment]
No, no Docker container. Though I guess I could try to reproduce this in a container.

**Comment by fhieber** [comment]
To be honest, I am not sure what could cause this. Your model configuration seems to be a char-based model with rather long sequence length. I am guessing that there is some memory scarcity with this, but I don't know why its deadlocking.
You could try to move the CheckpointDecoder to the cpu using `--decode-and-evaluate-use-cpu`.

**Comment by tdomhan** [comment]
Could you test whether the fix from the following branch works for you?
https://github.com/awslabs/sockeye/tree/forkserver
