### ISSUE TITLE
sockeye/git_version.py not deleted if tests fail

### ISSUE THREAD

**Issue by davvil** [awslabs/sockeye#54]
If a test fails while running `python setup.py test`, the file `sockeye/git_version.py` is not deleted. Running the tests again (and probably other commands in setup) fails with
```
Traceback (most recent call last):
  File "setup.py", line 128, in <module>
    with temporarily_write_git_hash(get_git_hash()):
  File "/Users/dvilar/anaconda3/lib/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "setup.py", line 48, in temporarily_write_git_hash
    raise RuntimeError("%s already exists, will not overwrite" % filename)
RuntimeError: sockeye/git_version.py already exists, will not overwrite
```

**Comment by tdomhan** [comment]
ohh, good catch!

**Comment by tdomhan** [comment]
https://github.com/awslabs/sockeye/pull/55
