### ISSUE TITLE
Support windows

### ISSUE THREAD

**Issue by hanayashiki** [awslabs/sockeye#567]
```
PS ....\sockeye\requirements> python3 -m sockeye.train
C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\sockeye\train.py", line 27, in <module>
    from . import arguments
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\sockeye\arguments.py", line 25, in <module>
    from . import data_io
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\sockeye\data_io.py", line 33, in <module>
    from . import vocab
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\sockeye\vocab.py", line 25, in <module>
    from . import utils
  File "C:\Users\Kiritsugu Emiya\AppData\Local\Programs\Python\Python36\lib\site-packages\sockeye\utils.py", line 19, in <module>
    import fcntl
ModuleNotFoundError: No module named 'fcntl'
```
when I tried to start `sockeye.train`, I got above. After googling I found that fcntl is linux-only, therefore I cannot run this .py on windows. Is there any workaround ?

**Comment by hanayashiki** [comment]
Seems deleting unused `import fcntl` in `sockeye\utils.py` can solve this.

**Comment by tdomhan** [comment]
ok, great to hear. `portalocker` seems to use `fcntl ` on posix hosts. Would you be willing to submit your change as a pull request? If so we'd be happy to merge this, so other Windows users can also profit from this.

**Comment by tdomhan** [comment]
@hanayashiki would you be able to check whether the PR solves your issue?

**Comment by tdomhan** [comment]
I will close the issue for now. Feel free to reopen or create a new should you encounter any other problems.
