### ISSUE TITLE
bug when re-loading 10 or more source vocabs

### ISSUE THREAD

**Issue by rudinger** [awslabs/sockeye#703]
I believe there is a bug in `vocab.load_source_vocabs` that is apparent only when 9 or more source-factors are in use (10+ total source vocabularies). The prepared source vocabularies for each of the source-factors are ordered by integer labels (`vocab.src.0.json`, `vocab.src.1.json`, `vocab.src.2.json` etc..) However, when these source vocabs are loaded from a sockeye-prepared data directory, they are sorted in alphabetic/string order, which means that `vocab.src.10.json` will come before `vocab.src.2.json` and so forth. This means that the vocabularies originally prepared by sockeye.prepare-data will not match the re-loaded vocabularies (see error below).

```
def load_source_vocabs(folder: str) -> List[Vocab]:
    """
    Loads source vocabularies from folder. The first element in the list is the primary source vocabulary.
    Other elements correspond to optional additional source factor vocabularies found in folder.
    :param folder: Source folder.
    :return: List of vocabularies.
    """
    return [vocab_from_json(os.path.join(folder, fname)) for fname in
            sorted([f for f in os.listdir(folder) if f.startswith(C.VOCAB_SRC_PREFIX)])]
```

Specifically, the issue arises when I try to resume training on a model where I'm using the `--prepared-data` flag, giving the following error:

```
Traceback (most recent call last):
  File "/home/rrudinger/.conda/envs/sockeye10/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/rrudinger/.conda/envs/sockeye10/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/rrudinger/.conda/envs/sockeye10/lib/python3.6/site-packages/sockeye/train.py", line 966, in <module>
    main()
  File "/home/rrudinger/.conda/envs/sockeye10/lib/python3.6/site-packages/sockeye/train.py", line 832, in main
    train(args)
  File "/home/rrudinger/.conda/envs/sockeye10/lib/python3.6/site-packages/sockeye/train.py", line 886, in train
    output_folder=output_folder)
  File "/home/rrudinger/.conda/envs/sockeye10/lib/python3.6/site-packages/sockeye/train.py", line 271, in create_data_iters_and_vocabs
    "Prepared data and resumed model source vocab %d do not match." % i)
  File "/home/rrudinger/.conda/envs/sockeye10/lib/python3.6/site-packages/sockeye/utils.py", line 121, in check_condition
    raise SockeyeError(error_message)
sockeye.utils.SockeyeError: Prepared data and resumed model source vocab 2 do not match.
```

Edit: Assuming that all sockeye-created source vocabs are of the form `*.N.json` where N is an integer, then I think the following would fix the issue:

```
def load_source_vocabs(folder: str) -> List[Vocab]:
    """
    Loads source vocabularies from folder. The first element in the list is the primary source vocabulary.
    Other elements correspond to optional additional source factor vocabularies found in folder.
    :param folder: Source folder.
    :return: List of vocabularies.
    """
    return [vocab_from_json(os.path.join(folder, fname)) for fname in
            sorted([f for f in os.listdir(folder) if f.startswith(C.VOCAB_SRC_PREFIX)], key=lambda x: int(x.split('.')[-2]))]

```

**Comment by fhieber** [comment]
Great catch, thank you! I can take a look in making the sorting cover the # of source factors > 10 case.

**Comment by rudinger** [comment]
You're welcome! I'm not currently working on a developer branch; just wanted to bring attention to this. The one-line modification above should do the trick. Thanks again!

**Comment by fhieber** [comment]
Ok, I'll do the change then. Thanks!
