### ISSUE TITLE
requirements for cuda 9.1

### ISSUE THREAD

**Issue by i55code** [awslabs/sockeye#787]
Hi, I am using Cuda 9.1, there is the following error. Where can I update Cuda directory? Thanks! 

sh train.sh 
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/sockeye/train.py", line 33, in <module>
    import mxnet as mx
  File "/usr/local/lib/python3.5/dist-packages/mxnet/__init__.py", line 24, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/usr/local/lib/python3.5/dist-packages/mxnet/context.py", line 24, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/usr/local/lib/python3.5/dist-packages/mxnet/base.py", line 213, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python3.5/dist-packages/mxnet/base.py", line 204, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory

**Comment by fhieber** [comment]
Hi @i55code, this does not seem to be an issue with Sockeye but with your MXNet installation. Your installed cuda version needs to match the MXNet version (mxnet-cu91).
