### ISSUE TITLE
Translation with --sample leads to gluon error

### ISSUE THREAD

**Issue by bricksdont** [awslabs/sockeye#855]
I am running into the following error, only if I use `--sample` instead of beam search:

```
[2020-08-25:17:03:08:ERROR:root:exception_hook] Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/translate.py", line 269, in <module>
    main()
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/translate.py", line 46, in main
    run_translate(args)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/translate.py", line 155, in run_translate
    input_is_json=args.json_input)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/translate.py", line 237, in read_and_translate
    chunk_time = translate(output_handler, chunk, translator)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/translate.py", line 260, in translate
    trans_outputs = translator.translate(trans_inputs)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/inference.py", line 836, in translate
    batch_translations = self._translate_nd(*self._get_inference_input(translator_inputs))
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/inference.py", line 1015, in _translate_nd
    max_output_lengths))
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/gluon/block.py", line 693, in __call__
    out = self.forward(*args)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/beam_search.py", line 666, in forward
    sample_best_hyp_indices)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/gluon/block.py", line 693, in __call__
    out = self.forward(*args)
  File "/net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/gluon/block.py", line 1146, in forward
    'Find all contexts = {}'.format(ctx_set))
ValueError: Find multiple contexts in the input, After hybridized, the HybridBlock only supports one input context. You can print the ele.context in the input arguments to inspect their contexts. Find all contexts = {gpu(0), cpu(0)}
```

I am calling Sockeye with a script such as

```
OMP_NUM_THREADS=1 python -m sockeye.translate \
                -i $data_sub/$corpus.pieces.src \
                -o $samples_sub_sub/$corpus.pieces.$seed.trg \
                -m $model_path \
                --sample \
                --seed $seed \
                --length-penalty-alpha 1.0 \
                --device-ids 0 \
                --batch-size 64 \
                --disable-device-locking
```

Sockeye and Mxnet versions:

```
[2020-08-25:17:03:03:INFO:sockeye.utils:log_sockeye_version] Sockeye version 2.1.17, commit 92a020a25cbe75935c700ce2f29b286b31a87189, path /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/sockeye/__init__.py
[2020-08-25:17:03:03:INFO:sockeye.utils:log_mxnet_version] MXNet version 1.6.0, path /net/cephfs/scratch/mathmu/map-volatility/venvs/sockeye3/lib/python3.5/site-packages/mxnet/__init__.py
```
Details that may be relevant:
- Running on a Tesla V100
- OS: Ubuntu 16.04.6 LTS
- the MXnet version in the CUDA 10.2 requirements file (https://github.com/awslabs/sockeye/blob/master/requirements/requirements.gpu-cu102.txt) is no longer available on Pypi. I had to install `mxnet-cu102mkl==1.6.0.post0`.

--------

Is anyone familiar with this error / is this a bug in Sockeye or Mxnet/Gluon?

**Comment by fhieber** [comment]
Hi @bricksdont!
This sounds like some tensors taking part in the hybridized computation during sampling live on another device than the GPU you are using.
My bet is that this is the problem: https://github.com/awslabs/sockeye/blob/master/sockeye/beam_search.py#L548
This array should also live on `self.context`. Do you want to create a PR?

**Comment by bricksdont** [comment]
Thanks Felix!

Will give this a try and make a PR if it solves the problem.

**Comment by bricksdont** [comment]
Yes, that's all it took to fix the problem. Thanks for the quick help.
