### ISSUE TITLE
when i trained the model getting the error :TypeError: __init__() got an unexpected keyword argument 'forget_bias'

### ISSUE THREAD

**Issue by abner2015** [awslabs/sockeye#88]
mxnet version:0.9.4

CMD: 
`python -m sockeye.train --source ./nmt_data/train2.en --target ./nmt_data/train2.vi --validation-source ./nmt_data/tst2012.en --validation-target ./nmt_data/tst2012.vi --output model
`

ERROR INFORMATION:
Traceback (most recent call last):
  File "/usr/lib/python3.4/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.4/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/new/software/mxnet_env/lib/python3.4/site-packages/sockeye/train.py", line 270, in <module>
    main()
  File "/home/new/software/mxnet_env/lib/python3.4/site-packages/sockeye/train.py", line 227, in main
    rnn_forget_bias=args.rnn_forget_bias)
  File "/home/new/software/mxnet_env/lib/python3.4/site-packages/sockeye/training.py", line 86, in __init__
    self._build_model_components(self.config.max_seq_len, fused, rnn_forget_bias)
  File "/home/new/software/mxnet_env/lib/python3.4/site-packages/sockeye/model.py", line 154, in _build_model_components
    fused_encoder)
  File "/home/new/software/mxnet_env/lib/python3.4/site-packages/sockeye/encoder.py", line 68, in get_encoder
    forget_bias=forget_bias))
  File "/home/new/software/mxnet_env/lib/python3.4/site-packages/sockeye/encoder.py", line 360, in __init__
    forget_bias=forget_bias)
  File "/home/new/software/mxnet_env/lib/python3.4/site-packages/sockeye/encoder.py", line 247, in __init__
    residual, forget_bias)
  File "/home/new/software/mxnet_env/lib/python3.4/site-packages/sockeye/rnn.py", line 45, in get_stacked_rnn
    cell = mx.rnn.LSTMCell(num_hidden=num_hidden, prefix=cell_prefix, forget_bias=forget_bias)
TypeError: __init__() got an unexpected keyword argument 'forget_bias'

**Comment by davvil** [comment]
Sockeye needs mxnet 0.10.0. Please update your installation and try again.

**Comment by fhieber** [comment]
@abner2015 Did you manage to get it running with MXNet 0.10.0? I am closing this for now, but feel free to reopen if the problem persists with the right version of MXNet.

**Comment by abner2015** [comment]
@fhieber @davvil 
Thanks
After updated the mxnet version , it is work.
