### ISSUE TITLE
Unable to translate using int8

### ISSUE THREAD

**Issue by jlquinn** [awslabs/sockeye#917]
Hi, I have sockeye 2.1.21 installed through pip and have trained a model on a v100.  I'm now trying to decode using int8 as follows:

sockeye-translate --config args.yaml --input junk.in -o junk.out -m $PWD --batch-size=100 --dtype=int8 --use-cpu

However, I get the following error:

[INFO:sockeye.model] Model version: 2.1.21
[INFO:sockeye.model] Loaded model config from "/u/jlquinn/jlquinn-mt/posenc/tfbase/base.75.1/config"
[INFO:sockeye.model] Disabling dropout layers for performance reasons
[ERROR:root] Uncaught exception
Traceback (most recent call last):
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/model.py", line 548, in load_model
    mx.library.load(path)
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/mxnet/library.py", line 38, in load
    raise MXNetError("load path %s does NOT exist" % path)
mxnet.base.MXNetError: load path /dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/libintgemm.so does NOT exist

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/bin/sockeye-translate", line 8, in <module>
    sys.exit(main())
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/translate.py", line 46, in main
    run_translate(args)
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/translate.py", line 88, in run_translate
    mc_dropout=args.mc_dropout)
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/model.py", line 664, in load_models
    forward_pass_cache_size=forward_pass_cache_size)
  File "/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/model.py", line 552, in load_model
    "operator then set the path using intgemm_custom_lib in the config file." % path)
NotImplementedError: 8-bit int inference requested but intgemm was not compiled into MXNet and a custom operator library was not found in `/dccstor/jlquinn-mt/nmt-env/conda37.x86/envs/pt15/lib/python3.7/site-packages/sockeye/libintgemm.so`.  Compile the custom operator then set the path using intgemm_custom_lib in the config file.

How do I obtain libintgemm.so?  Is this just the library from https://github.com/kpu/intgemm?  Is there a package to install this library?  If not, how do I build it to be compatible with the installed mxnet package?

**Comment by fhieber** [comment]
Hi @jlquinn,
you need to use an MXNet version with intgemm support.
The Dockerfile for CPU inference [here](https://github.com/awslabs/sockeye/blob/master/sockeye_contrib/docker/Dockerfile.cpu#L101) uses a dedicated custom commit of MXNet, when intgemm support was not yet fully merged in MXNet. You can try this. 
Intgemm support has been added to more recent versions of MXNet, but they are not released yet (1.8 and higher). You can either wait for MXNet 1.8, or use MXNet's `1.x` branch to compile a version of MXNet that has intgemm support enabled by default.
