### ISSUE TITLE
Windows 10 - Python3.7 - IndexError: tensors used as indices must be long, byte or bool tensors

### ISSUE THREAD

**Issue by RamoramaInteractive** [awslabs/sockeye#989]
After Executing the code from the first tutorial 

`sockeye-train -s data/train.source -t data/train.target -vs data/dev.source -vt data/dev.target --encoder transformer --decoder transformer --num-layers 1:1 --num-embed 32 --transformer-model-size 32 --transformer-feed-forward-num-hidden 64 --transformer-attention-heads 4 --max-num-checkpoint-not-improved 3 -o seqcopy_model`

on my Windows 10 PC which runs a NVIDIA GeForce GTX960 2GB

```
Traceback (most recent call last):
  File "D:\Anaconda\envs\sockeye\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Anaconda\envs\sockeye\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Anaconda\envs\sockeye\Scripts\sockeye-train.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "D:\Anaconda\envs\sockeye\lib\site-packages\sockeye\train_pt.py", line 848, in main
    train(args)
  File "D:\Anaconda\envs\sockeye\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "D:\Anaconda\envs\sockeye\lib\site-packages\sockeye\train_pt.py", line 924, in train
    output_folder=output_folder)
  File "D:\Anaconda\envs\sockeye\lib\site-packages\sockeye\train_pt.py", line 400, in create_data_iters_and_vocabs
    batch_sentences_multiple_of=args.batch_sentences_multiple_of)
  File "D:\Anaconda\envs\sockeye\lib\site-packages\sockeye\data_io_pt.py", line 974, in get_training_data_iters
    permute=permute)
  File "D:\Anaconda\envs\sockeye\lib\site-packages\sockeye\data_io_pt.py", line 1812, in __init__
    self.reset()
  File "D:\Anaconda\envs\sockeye\lib\site-packages\sockeye\data_io_pt.py", line 1832, in reset
    self.data_permutations, self.inverse_data_permutations = get_permutations(self.data.get_bucket_counts())
  File "D:\Anaconda\envs\sockeye\lib\site-packages\sockeye\data_io_pt.py", line 1501, in get_permutations
    inverse_data_permutation[data_permutation] = torch.arange(num_samples)
IndexError: tensors used as indices must be long, byte or bool tensors
```

According to `pip3 freeze` the following packages are installed:

```
certifi==2021.10.8
mkl-fft==1.3.1
mkl-random @ file:///C:/ci/mkl_random_1626186163140/work
mkl-service==2.4.0
numpy==1.21.4
olefile==0.46
Pillow==8.4.0
portalocker==2.3.2
pyaml==21.10.1
pywin32==302
PyYAML==6.0
sacrebleu==1.4.14
six @ file:///tmp/build/80754af9/six_1623709665295/work
sockeye==3.0.0
torch==1.10.0
torchaudio==0.10.0
torchvision==0.11.1
typing_extensions==4.0.1
wincertstore==0.2
```

**Comment by fhieber** [comment]
We are not testing against Windows environments or officially supporting Windows. There seems to be some differences in how PyTorch handles dtype conversions on Windows, compared to Linux or MacOs (which are covered by our continuous integration tests).
You could try and change the code in the offending line to:
`inverse_data_permutation[data_permutation.long()] = torch.arange(num_samples)`
to see if this fixes the issue.

**Comment by RamoramaInteractive** [comment]
This works for me! Thanks!

**Comment by fhieber** [comment]
We can't easily support Windows, but here is a PR that might fix this particular issue for Windows users: https://github.com/awslabs/sockeye/pull/990

**Comment by RamoramaInteractive** [comment]
Thanks for this pull request.

After editing the file _data_io_pt.py_ you have to train as administrator.

**Comment by fhieber** [comment]
if you re-install the latest version this should no longer be necessary.
